# Generated by Django 5.1.4 on 2024-12-17 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Issued', 'Issued')], max_length=20)),
            ],
        ),
    ]
